# -*- coding: utf-8 -*-
# 6 套主题配置：每套 = 独立配色 + 独立架构(layout)标识 + 专属点缀
# layout: A=竖向七组件滚动 / B=左侧固定Hero栏+右滚 / C=全局Bento拼贴 / D=时间轴脊背 / E=对话气泡 / F=展厅分区导航

THEMES = [
    {
        "id": "creative_light",
        "name": "Creative_Light",
        "cn": "画廊风",
        "layout": "A",
        "desc": "策展人 · 展签语言 · 通用创作者",
        "bg": "#f6f1e7",
        "surface": "#fffdf8",
        "ink": "#2b2620",
        "muted": "#8a7f6d",
        "accent": "#c8861d",
        "accent2": "#1f4032",
        "line": "#e3d9c4",
        "tag": "#f0e6d2",
        "radius": "18px",
        "font": "-apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif",
    },
    {
        "id": "midnight_ink",
        "name": "Midnight_Ink",
        "cn": "深夜墨稿",
        "layout": "B",
        "desc": "杂志 · 文艺 · 写手/独立开发者",
        "bg": "#0f1419",
        "surface": "#161d26",
        "ink": "#e8e6df",
        "muted": "#8b94a0",
        "accent": "#c0392b",
        "accent2": "#e8e6df",
        "line": "#26303c",
        "tag": "#1d2630",
        "radius": "10px",
        "font": "'Songti SC', Georgia, 'PingFang SC', serif",
    },
    {
        "id": "bento_mono",
        "name": "Bento_Mono",
        "cn": "极简模块",
        "layout": "C",
        "desc": "设计感 · 极简 · 设计师/极简控",
        "bg": "#0e0e0e",
        "surface": "#1a1a1a",
        "ink": "#f5f5f5",
        "muted": "#888",
        "accent": "#00ff9d",
        "accent2": "#ffffff",
        "line": "#2a2a2a",
        "tag": "#222",
        "radius": "22px",
        "font": "'Helvetica Neue', 'PingFang SC', sans-serif",
    },
    {
        "id": "timeline_quest",
        "name": "Timeline_Quest",
        "cn": "成长主线",
        "layout": "D",
        "desc": "进阶 · 有温度职场 · 职场/接单党",
        "bg": "#efe6d3",
        "surface": "#fbf6ea",
        "ink": "#3a2e1f",
        "muted": "#9a8869",
        "accent": "#b5651d",
        "accent2": "#3a2e1f",
        "line": "#d8c7a3",
        "tag": "#e7dcc2",
        "radius": "12px",
        "font": "'PingFang SC', 'Microsoft YaHei', sans-serif",
    },
    {
        "id": "chat_me",
        "name": "Chat_Me",
        "cn": "对话式",
        "layout": "E",
        "desc": "社交破冰 · 年轻 · 社群/年轻人",
        "bg": "#f2f2f2",
        "surface": "#ffffff",
        "ink": "#1a1a1a",
        "muted": "#999",
        "accent": "#07c160",
        "accent2": "#576b95",
        "line": "#e5e5e5",
        "tag": "#eafaf1",
        "radius": "20px",
        "font": "'PingFang SC', 'Microsoft YaHei', sans-serif",
    },
    {
        "id": "gallery_route",
        "name": "Gallery_Route",
        "cn": "展览路线",
        "layout": "F",
        "desc": "策展进阶 · 多面 · 个人IP/多身份者",
        "bg": "#f4f1ee",
        "surface": "#fff",
        "ink": "#33312e",
        "muted": "#a39b92",
        "accent": "#7c93a6",
        "accent2": "#c9a9a6",
        "line": "#e2dbd4",
        "tag": "#ece6df",
        "radius": "16px",
        "font": "'PingFang SC', 'Microsoft YaHei', sans-serif",
    },
]
